paths:
  /diaries/list:
    get:
      tags:
        - Diary
      summary: 전체 일기 조회
      responses:
        '200':
          description: 전체 일기 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultType:
                    type: string
                    example: SUCCESS
                  error:
                    type: object
                    nullable: true
                    example: null
                  diary:
                    type: array
                    items:
                      type: object
                      properties:
                        diary_id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        diary_date:
                          type: string
                          format: date

  /diaries/date/{yyyymmdd}:
    get:
      tags:
        - Diary
      summary: 특정 날짜 일기 조회
      parameters:
        - name: yyyymmdd
          in: path
          description: 조회할 날짜 (YYYY-MM-DD)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 일기 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultType:
                    type: string
                    example: SUCCESS
                  message:
                    type: string
                    example: 일기 조회 완료
                  diary:
                    type: object
                    nullable: true
                    properties:
                      diary_id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                      diary_date:
                        type: string
                        format: date
        '400':
          description: 잘못된 날짜 형식
        '404':
          description: 해당 날짜에 일기 없음

  /diaries/{diary_id}:
    get:
      tags:
        - Diary
      summary: 일기 상세 조회
      parameters:
        - name: diary_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 상세 일기 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 상세 일기 조회 완료
                  diary:
                    type: object
                    properties:
                      diary_id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                      diary_date:
                        type: string
                        format: date
        '403':
          description: 접근 권한 없음
        '404':
          description: 일기 없음

  /diaries:
    post:
      tags:
        - Diary
      summary: 일기 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                diary_date:
                  type: string
                  format: date
      responses:
        '200':
          description: 일기 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 일기 등록 완료
                  diary_id:
                    type: integer
        '400':
          description: 등록 실패 (유효하지 않은 데이터)
        '404':
          description: 사용자 없음

  /diaries/{diary_id}:
    put:
      tags:
        - Diary
      summary: 일기 수정
      parameters:
        - name: diary_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                diary_date:
                  type: string
                  format: date
      responses:
        '200':
          description: 일기 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 일기 수정 완료
                  diary_id:
                    type: integer
        '400':
          description: 유효하지 않은 데이터
        '404':
          description: 일기 또는 사용자 없음

    delete:
      tags:
        - Diary
      summary: 일기 삭제
      parameters:
        - name: diary_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 일기 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 일기 삭제 완료
                  diary_id:
                    type: integer
        '404':
          description: 일기 또는 사용자 없음
