paths:
  /users/me:
    get:
      tags: [Users]
      summary: 사용자 개인정보 조회
      responses:
        '200':
          description: 개인정보 조회 성공
          content:
            application/json:
              schema:
                type: object  
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  birth:
                    type: string
                    format: date
                  job:
                    type: string
                  avg_ready_time:
                    type: integer
                  duration_time:
                    type: integer
                  alarm_check_time:
                    type: string
                    format: time
    put:
      tags: [Users]
      summary: 사용자 개인정보 수정
      security:
        -bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                birth:
                  type: string
                  format: date
                job:
                  type: string
                avg_ready_time:
                  type: integer
                duration_time:
                  type: integer
                alarm_check_time:
                  type: string
                  format: time
      responses:
        '200':
          description: 개인정보 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 개인정보 수정 완료
  /users/me/auto-alarm-check-time:
    get:
      tags: [Users]
      summary: 자동 알람 확인 시간 조회
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 자동 알람 확인 시간 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  alarm_check_time:
                    type: string
                    format: time
    put:
      tags: [Users]
      summary: 자동 알람 확인 시간 수정
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                alarm_check_time:
                  type: string
                  format: time
      responses:
        '200':
          description: 자동 알람 확인 시간 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
